package com.revature.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2021-03-25T17:41:56.881-04:00
 * Generated source version: 3.3.0
 *
 */
@WebServiceClient(name = "personService",
                  wsdlLocation = "http://localhost:8080/SOAPGreeting/personservice?wsdl",
                  targetNamespace = "http://ws.revature.com/")
public class PersonService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.revature.com/", "personService");
    public final static QName PersonServiceImplPort = new QName("http://ws.revature.com/", "PersonServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/SOAPGreeting/personservice?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PersonService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/SOAPGreeting/personservice?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PersonService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PersonService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public PersonService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PersonService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PersonService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns PersonService
     */
    @WebEndpoint(name = "PersonServiceImplPort")
    public PersonService getPersonServiceImplPort() {
        return super.getPort(PersonServiceImplPort, PersonService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonService
     */
    @WebEndpoint(name = "PersonServiceImplPort")
    public PersonService getPersonServiceImplPort(WebServiceFeature... features) {
        return super.getPort(PersonServiceImplPort, PersonService.class, features);
    }

}
