package com.revature.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2021-03-25T17:41:56.864-04:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://ws.revature.com/", name = "PersonService")
@XmlSeeAlso({ObjectFactory.class})
public interface PersonService {

    @WebMethod
    @RequestWrapper(localName = "addPerson", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.AddPerson")
    @ResponseWrapper(localName = "addPersonResponse", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.AddPersonResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String addPerson(
        @WebParam(name = "arg0", targetNamespace = "")
        com.revature.ws.Person arg0
    );

    @WebMethod
    @RequestWrapper(localName = "updatePersonName", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.UpdatePersonName")
    @ResponseWrapper(localName = "updatePersonNameResponse", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.UpdatePersonNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String updatePersonName(
        @WebParam(name = "arg0", targetNamespace = "")
        com.revature.ws.Person arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "updateAge", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.UpdateAge")
    @ResponseWrapper(localName = "updateAgeResponse", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.UpdateAgeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean updateAge(
        @WebParam(name = "arg0", targetNamespace = "")
        com.revature.ws.Person arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );
}
