package com.revature.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2021-03-25T17:41:57.069-04:00
 * Generated source version: 3.3.0
 *
 */
@WebServiceClient(name = "testingGenService",
                  wsdlLocation = "http://localhost:8080/SOAPGreeting/testingservice?wsdl",
                  targetNamespace = "http://ws.revature.com/")
public class TestingGenService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.revature.com/", "testingGenService");
    public final static QName TestingGenImplPort = new QName("http://ws.revature.com/", "TestingGenImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/SOAPGreeting/testingservice?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TestingGenService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/SOAPGreeting/testingservice?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TestingGenService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TestingGenService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestingGenService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public TestingGenService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TestingGenService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TestingGenService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns TestingGen
     */
    @WebEndpoint(name = "TestingGenImplPort")
    public TestingGen getTestingGenImplPort() {
        return super.getPort(TestingGenImplPort, TestingGen.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestingGen
     */
    @WebEndpoint(name = "TestingGenImplPort")
    public TestingGen getTestingGenImplPort(WebServiceFeature... features) {
        return super.getPort(TestingGenImplPort, TestingGen.class, features);
    }

}
