package com.revature.ws;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2021-03-25T17:41:57.058-04:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://ws.revature.com/", name = "TestingGen")
@XmlSeeAlso({ObjectFactory.class})
public interface TestingGen {

    @WebMethod
    @RequestWrapper(localName = "getTestingMessage", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.GetTestingMessage")
    @ResponseWrapper(localName = "getTestingMessageResponse", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.GetTestingMessageResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getTestingMessage();
}
